export default {
  FETCH_EMPLOYEES_DATA_INITIATE: "FETCH_EMPLOYEES_DATA_INITIATE",
  FETCH_EMPLOYEES_DATA_SUCCESS: "FETCH_EMPLOYEES_DATA_SUCCESS",
  FETCH_EMPLOYEES_DATA_FAILURE: "FETCH_EMPLOYEES_DATA_FAILURE",

  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  EDIT_EMPLOYEE: "EDIT_EMPLOYEE",
  SELECT_EMPLOYEE: "SELECT_EMPLOYEE",
};
